database_container_name := "server_postgres"

# Server
export DATABASE_URL := "postgres://aluno:123@localhost:5432/senac"
export SECRET_KEY := "senac"

set quiet

[private]
default:
    just --list

# Run unit tests
[group("dev")]
test: require-database
    gleam test

# Run application
[group("dev")]
run: require-database
    gleam run

# Build container
[group("docker")]
build:
    docker compose build

# Start containers
[group("docker")]
up:
    docker compose up -d

# Stop containers
[group("docker")]
down:
    docker compose down -v

# Generate SQL queries
[group("dev")]
generate-sql:
    gleam run -m squirrel

# Start the database container
[group("database")]
start-database:
    docker run --rm -d --name {{ database_container_name }} \
      -e POSTGRES_USER="aluno" \
      -e POSTGRES_PASSWORD="123" \
      -e POSTGRES_DB="senac" \
      -v "./postgres:/docker-entrypoint-initdb.d" \
      -p "5432:5432" \
      docker.io/postgres:18-alpine
    echo {{ GREEN }}"  PostgreSQL is now running"{{ NORMAL }}

# Restart the database container
[group("database")]
restart-database:
    just stop-database
    echo {{ GREEN }}"󰜉  Rebuilding PostgreSQL database"{{ NORMAL }}
    just start-database

# Stop the database container
[group("database")]
stop-database: require-database
    docker container stop {{ database_container_name }}
    echo {{ GREEN }}"  Stopped the database container"{{ NORMAL }}

# Check if the database is active
[no-exit-message]
[private]
require-database:
    docker container exists {{ database_container_name }} \
    || ( echo {{ YELLOW }}"  Database container needs to be running"{{ NORMAL }} \
    && just --usage start-database \
    && exit 1 )
